apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  name: hightowerlabs-kcc-storage-bucket
spec:
  location: US
  uniformBucketLevelAccess: true
  lifecycleRule:
    - action:
       type: Delete
      condition:
       age: 7
